# Generated by Django 5.0.2 on 2024-03-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField(blank=True)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('num_views', models.IntegerField(default=0)),
            ],
        ),
    ]
