# Generated by Django 4.2.3 on 2024-03-23 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
